### ISSUE TITLE
fail2ban and python 3.9

### ISSUE THREAD

**Issue by HQuest** [fail2ban/fail2ban#3335]
Not sure Python 3.9 is supported by fail2ban - can't find any references to it. Below is a list of warnings and failures to install and run fail2ban with Python 3.9 (Slackware -current). The successful components were trimmed out, not particularly being relevant. While the below is using the current git repo code, I was unable to find a way to run any of the releases of fail2ban with Python 3.9. It seems working with 3.8, though.

```
$ python -V
Python 3.9.13
$ ./setup.py install
running install
/usr/lib64/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
byte-compiling /usr/lib64/python3.9/site-packages/fail2ban/server/ipdns.py to ipdns.cpython-39.pyc
  File "/usr/lib64/python3.9/site-packages/fail2ban/server/ipdns.py", line 335
                                        mask = ~(0xFFFFFFFFL >> cidr)
                                                           ^
SyntaxError: invalid syntax
byte-compiling /usr/lib64/python3.9/site-packages/fail2ban/tests/filtertestcase.py to filtertestcase.cpython-39.pyc
  File "/usr/lib64/python3.9/site-packages/fail2ban/tests/filtertestcase.py", line 1778
                                   % m for m in 53, 54, 57, 58])
                                                  ^
SyntaxError: invalid syntax

byte-compiling /usr/lib64/python3.9/site-packages/fail2ban/tests/misctestcase.py to misctestcase.cpython-39.pyc
  File "/usr/lib64/python3.9/site-packages/fail2ban/tests/misctestcase.py", line 259
                                print deep_function(3)
                                      ^
SyntaxError: invalid syntax

writing top-level names to fail2ban.egg-info/top_level.txt
/usr/lib64/python3.9/site-packages/setuptools/command/egg_info.py:643: SetuptoolsDeprecationWarning: Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
  warnings.warn(
```

Then, after files are installed:
```
$ fail2ban-client -h
Traceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/usr/lib64/python3.9/site-packages/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/usr/lib64/python3.9/site-packages/fail2ban/server/utils.py", line 56, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems
```'

**Comment by sebres** [comment]
Fail2ban actually supports 3.11.0-beta3, see latest CI [GHA](https://github.com/fail2ban/fail2ban/runs/7881607889?check_suite_focus=true)

As for the issue - don't forget 2to3, see https://github.com/fail2ban/fail2ban/issues/3323#issuecomment-1191871144

**Comment by gaby64** [comment]
Why do we still need to 2to3?

**Comment by sebres** [comment]
> Why do we still need to 2to3?

Because fail2ban core is still 2.x based. 
I know that 2.7 has already reached end of life, but there were many boxes yet, which are still 2.7 based.
Yes, it will slowly be time to switch to 3.x... 
No, it hasn't happened yet.
