### ISSUE TITLE
[BR]: Fails to build for Python 3.15

### ISSUE THREAD

**Issue by hobbes1069** [fail2ban/fail2ban#4126]
### Environment:
Fedora Rawhide (future f45 release)

- Fail2Ban version  : 1.1.0
- OS, including release name/version : Fedora Rawhide (future 45 release)

### The issue:

```
ail2ban fails to build with Python 3.15.0a3.

======================================================================
ERROR: testActionWithDB (fail2ban.tests.databasetestcase.DatabaseTest.testActionWithDB)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/fail2ban-1.1.0-build/fail2ban-1.1.0/fail2ban/tests/databasetestcase.py", line 575, in testActionWithDB
    actions.add(
    ~~~~~~~~~~~^
    	"action_checkainfo",
     ^^^^^^^^^^^^^^^^^^^^
    	os.path.join(TEST_FILES_DIR, "action.d/action_checkainfo.py"),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    	{})
     ^^^
  File "/builddir/build/BUILD/fail2ban-1.1.0-build/fail2ban-1.1.0/fail2ban/server/actions.py", line 147, in add
    customActionModule = self._load_python_module(pythonModule)
  File "/builddir/build/BUILD/fail2ban-1.1.0-build/fail2ban-1.1.0/fail2ban/server/actions.py", line 94, in _load_python_module
    mod = Utils.load_python_module(pythonModule)
  File "/builddir/build/BUILD/fail2ban-1.1.0-build/fail2ban-1.1.0/fail2ban/server/utils.py", line 356, in load_python_module
    pythonModuleName, pythonModule).load_module()
                                    ^^^^^^^^^^^
AttributeError: 'SourceFileLoader' object has no attribute 'load_module'. Did you mean: 'exec_module'?
```

#### Any additional information

https://docs.python.org/3.15/whatsnew/3.15.html

`load_module` is no longer supported.

Use `zipimporter.zipimporter.exec_module()` instead

**Comment by sebres** [comment]
Confirmed.
https://github.com/fail2ban/fail2ban/actions/runs/20645048106/job/59281753288
WiP.
