### ISSUE TITLE
[BR]: ERROR: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)

### ISSUE THREAD

**Issue by Doublefire-Chen** [fail2ban/fail2ban#3717]
### Environment:

- Fail2Ban version  :  0.11.1-1
- OS, including release name/version :  Ubuntu 20.04.6 LTS
- [x] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [x] Some customizations were done to the configuration (provide details below is so)

### The issue:

I can not launch fail2ban in my OS. I have searched before and found https://github.com/fail2ban/fail2ban/issues/3142, it says "[1.0.2](https://github.com/fail2ban/fail2ban/releases/tag/1.0.2) it is already fixed." However, my version is higher than 1.0.2, it still failed to launch. Maybe it is related to python version as we have different python version.

#### Steps to reproduce
```
apt update
apt install fail2ban
fail2ban-client status
```
#### Expected behavior
ERROR: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
2024-04-10 18:15:42,854 fail2ban                [278878]: ERROR   Init of command line failed

### Configuration, dump and another helpful excerpts
```
fail2ban-client -d
ERROR: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.11/collections/__init__.py)
2024-04-10 18:18:10,330 fail2ban                [278883]: ERROR   Init of command line failed
```

**Comment by sebres** [comment]
> However, my version is higher than 1.0.2

No it is not, your version is 0.11.x that is obviously smaller than 1.0.x (`0 < 1`).
And there is indeed no 0.11.x version which could work with python >= 3.11.

You could try to install it from our releases provided here (no idea it'd be compatible with  Ubuntu 20.04.6, but I don't see why not) - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually#manual-installation-of-debian-upstream-package-released-here

**Comment by Doublefire-Chen** [comment]
After changing apt source and reinstall fail2ban, it works for me though its version is 0.11.2
```
root@Ali-BJ:~# fail2ban-client version
0.11.2
root@Ali-BJ:~#
```

**Comment by sebres** [comment]
> it works for me though its version is 0.11.2

Then it either uses different python version (see `fail2ban-python --version`) or it was patched by the maintainers of that repo.
