### ISSUE TITLE
Upgrade to Python 3.8.1 broke utils.py

### ISSUE THREAD

**Issue by egberts** [fail2ban/fail2ban#2845]
### Environment:

- Fail2Ban version (including any possible distribution suffixes): master (commit 960e30cfcdae7e2c81f74046efdbff1606f9774e)
- OS, including release name/version: Linux arca 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux

- [ ] Fail2Ban installed via OS/distribution mechanisms
- [x] You have not applied any additional foreign patches to the codebase
- [ ] Some customizations were done to the configuration (provide details below is so)

### The issue:

Python 3.8.1 removed itemiters() from dictionary.  As a result, `fail2ban-client` failed.
#### Steps to reproduce

```
# fresh install Debian Bullseye  11
git clone https://github.com/fail2ban/fail2ban.git
cd fail2ban
python3.8.6 ./setup.py install 
cp build/fail2ban.service /etc/systemd/system
systemctl daemon-reload
systemctl start fail2ban.service
fail2ban-client status
```

#### Expected behavior

No error during `fail2ban-client` due to Python obsoleted function uages.

#### Observed behavior

As a result, `fail2ban-client` failed with:
```console
$ fail2ban-client status
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/home/steve/work/github/fail2ban/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/home/steve/work/github/fail2ban/fail2ban/server/utils.py", line 60, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'
steve@arca:~/work/github/fail2ban$ python3.8
Python 3.8.6 (default, Sep 25 2020, 09:36:53) 
```

#### Any additional information

* https://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems
*

**Comment by egberts** [comment]
INVALID.   My github was at 0.11, pulled latest.

**Comment by egberts** [comment]
origin/0.11 broke, reopening  this.



* dict methods dict.keys(), dict.items() and dict.values() return “views” instead of lists. For example, this no longer works: k = d.keys(); k.sort(). Use k = sorted(d) instead (this works in Python 2.5 too and is just as efficient).
*  Also, the dict.iterkeys(), dict.iteritems() and dict.itervalues() methods are no longer supported.

Reference: https://stackoverflow.com/questions/20444340/iter-values-item-in-dictionary-does-not-work/20444345#20444345

**Comment by egberts** [comment]
Authoritative details in: https://docs.python.org/3.1/whatsnew/3.0.html#views-and-iterators-instead-of-lists

**Comment by egberts** [comment]
Looks like a versioning design decision is going to have to be made.   perhaps 0.20 for Python3-only?

**Comment by RussellTaylor83** [comment]
This is still a problem (I cannot run fail2ban with python 3.6.9), is there a solution please?

**Comment by sebres** [comment]
> This is still a problem (I cannot run fail2ban with python 3.6.9)...

Which fail2ban version and what exactly is the issue?
Although fail2ban had never any problem with python 3.6.

**Comment by RussellTaylor83** [comment]
Thank you sebres. I've just cloned master, logs say:

`commit 095aeda8407b433098df35424cde2764a09566a6 (HEAD -> master, origin/master, origin/HEAD)
Merge: 80805cab 3fb02527
Author: sebres <serg.brester@sebres.de>
Date:   Thu Dec 2 18:56:19 2021 +0100

    Merge branch '0.11'`
    
The issue is

`root@myserver:~/fail2ban# fail2ban-client -h
Traceback (most recent call last):
  File "/usr/local/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/usr/local/lib/python3.6/dist-packages/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/usr/local/lib/python3.6/dist-packages/fail2ban/server/utils.py", line 60, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'`

**Comment by sebres** [comment]
How did you install it? Forgotten `2to3` maybe?
Source code of fail2ban is based on python 2.x, you need to call `2to3` to be able to start/install it with python 3.x

**Comment by RussellTaylor83** [comment]
Thank you sebres, that's certainly true. I followed the instructions in the README (https://github.com/fail2ban/fail2ban). I will try to find 2to3 and try that.

**Comment by RussellTaylor83** [comment]
For future readers there are instructions on Python3 installation here - https://github.com/fail2ban/fail2ban/wiki/How-to-install-or-upgrade-fail2ban-manually
