### ISSUE TITLE
Quick Python3 update (legacy from python2)

### ISSUE THREAD

**Issue by zchs** [fail2ban/fail2ban#1694]
### The issue:

current git fails on python3

#### Steps to reproduce

fail2ban-client --help

#### Expected behavior
Lists help options

#### Observed behavior
```
Traceback (most recent call last):
  File "/usr/bin/fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/usr/lib64/python3.4/site-packages/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/usr/lib64/python3.4/site-packages/fail2ban/server/utils.py", line 54, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'
```

#### Fix
```diff
diff --git a/fail2ban/server/utils.py b/fail2ban/server/utils.py
index 57da495a..b90742e0 100644
--- a/fail2ban/server/utils.py
+++ b/fail2ban/server/utils.py
@@ -51,7 +51,7 @@ _RETCODE_HINTS = {
 
 # Dictionary to lookup signal name from number
 signame = dict((num, name)
-       for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
+       for name, num in signal.__dict__.items() if name.startswith("SIG"))
 
 class Utils():
        """Utilities provide diverse static methods like executes OS shell commands, etc.

```

**Comment by sebres** [comment]
> current git fails on python3

What is for you current git? (Which branch?)

> 'dict' object has no attribute 'iteritems

How have you installed it?
Fail2ban is written for both python (see README), so work with python2 >= 2.6 as well as python3 >= 3.2
If it should be used with python3, the command `fail2ban-2to3` should be executed firstly.

Closed as invalid.

**Comment by mikenye** [comment]
Can this be re-opened? I can confirm the problem still exists in v0.11.1 on systems that only have python3.

```
root@7ceb950e7bc5:/src/fail2ban/bin# python -V
Python 3.7.3
```

```
root@7ceb950e7bc5:/src/fail2ban/bin# git branch
* (HEAD detached at 0.11.1)
  master
```

```
root@7ceb950e7bc5:/src/fail2ban/bin# ./fail2ban-client -h
Traceback (most recent call last):
  File "./fail2ban-client", line 34, in <module>
    from fail2ban.client.fail2banclient import exec_command_line, sys
  File "/usr/local/lib/python3.7/dist-packages/fail2ban/client/fail2banclient.py", line 39, in <module>
    from ..server.utils import Utils
  File "/usr/local/lib/python3.7/dist-packages/fail2ban/server/utils.py", line 60, in <module>
    for name, num in signal.__dict__.iteritems() if name.startswith("SIG"))
AttributeError: 'dict' object has no attribute 'iteritems'
```

```
root@7ceb950e7bc5:/src/fail2ban/bin# ./fail2ban-server -h
Usage: fail2ban-server [OPTIONS]

Fail2Ban v0.11.1 reads log file that contains password failure report
and bans the corresponding IP addresses using firewall rules.

Options:
    -c <DIR>                configuration directory
    -s <FILE>               socket path
    -p <FILE>               pidfile path
    --loglevel <LEVEL>      logging level
    --logtarget <TARGET>    logging target, use file-name or stdout, stderr, syslog or sysout.
    --syslogsocket auto|<FILE>
    -d                      dump configuration. For debugging
    --dp, --dump-pretty     dump the configuration using more human readable representation
    -t, --test              test configuration (can be also specified with start parameters)
    -i                      interactive mode
    -v                      increase verbosity
    -q                      decrease verbosity
    -x                      force execution of the server (remove socket file)
    -b                      start server in background (default)
    -f                      start server in foreground
    --async                 start server in async mode (for internal usage only, don't read configuration)
    --timeout               timeout to wait for the server (for internal usage only, don't read configuration)
    --str2sec <STRING>      convert time abbreviation format to seconds
    -h, --help              display this help message
    -V, --version           print the version (-V returns machine-readable short format)

Report bugs to https://github.com/fail2ban/fail2ban/issues
```

```
root@7ceb950e7bc5:/src/fail2ban/bin# ./fail2ban-server -V
0.11.1
```

**Comment by sebres** [comment]
> Can this be re-opened? I can confirm the problem still exists in v0.11.1 on systems that only have python3.
/src/fail2ban/bin# ./fail2ban-client -h
...
AttributeError: 'dict' object has no attribute 'iteritems'

As long as we still supporting fail2ban for 2.x (and 3to2 is not so trivial as vice versa), I can only repeat my previous statement:
"If it should be used with python3, the command `fail2ban-2to3` should be executed firstly."

**Comment by mikenye** [comment]
Yep sorry, I missed this part and deleted my comment when I realised. Apologies.
