### ISSUE TITLE
python 3.9 threading changes

### ISSUE THREAD

**Issue by opoplawski** [fail2ban/fail2ban#2646]
Copied from https://bugzilla.redhat.com/show_bug.cgi?id=1808347

            Bug ID: 1808347
           Summary: fail2ban fails to build with Python 3.9: uses removed
                    threading.Thread.isAlive()
           Product: Fedora
           Version: rawhide
            Status: NEW
         Component: fail2ban
          Assignee: orion@nwra.com
          Reporter: mhroncok@redhat.com
        QA Contact: extras-qa@fedoraproject.org
                CC: anon.amish@gmail.com, axel.thimm@atrpms.net,
                    cstratak@redhat.com, mhroncok@redhat.com,
                    mplch@redhat.com, orion@nwra.com, vonsch@gmail.com
            Blocks: 1785415 (PYTHON39)
  Target Milestone: ---
    Classification: Fedora

fail2ban fails to build with Python 3.9.0a4.
```
ERROR: test_del_file
(fail2ban.tests.filtertestcase.MonitorFailures<FilterPoll>(/tmp/monitorfailures_FilterPoll__nshi9c2fail2ban))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./fail2ban/tests/filtertestcase.py", line 987, in setUp
    self._sleep_4_poll()
  File "./fail2ban/tests/filtertestcase.py", line 1008, in _sleep_4_poll
    Utils.wait_for(self.filter.isAlive, _maxWaitTime(5))
AttributeError: 'FilterPoll' object has no attribute 'isAlive'
```

And more. This looks like:

See https://docs.python.org/3.9/whatsnew/3.9.html#removed

"The isAlive() method of threading.Thread has been removed. It was deprecated
since Python 3.8. Use is_alive() instead."

For the build logs, see:
https://copr-be.cloud.fedoraproject.org/results/@python/python3.9/fedora-rawhide-x86_64/01255081-fail2ban/

For all our attempts to build fail2ban with Python 3.9, see:
https://copr.fedorainfracloud.org/coprs/g/python/python3.9/package/fail2ban/

Testing and mass rebuild of packages is happening in copr. You can follow these
instructions to test locally in mock if your package builds with Python 3.9:
https://copr.fedorainfracloud.org/coprs/g/python/python3.9/

Let us know here if you have any questions.

Python 3.9 will be included in Fedora 33. To make that update smoother, we're
building Fedora packages with early pre-releases of Python 3.9.
A build failure prevents us from testing all dependent packages (transitive
[Build]Requires), so if this package is required a lot, it's important for us
to get it fixed soon.
We'd appreciate help from the people who know this package best, but if you
don't want to work on this now, let us know so we can try to work around it on
our side.

Referenced Bugs:

https://bugzilla.redhat.com/show_bug.cgi?id=1785415
[Bug 1785415] Python 3.9

**Comment by sebres** [comment]
Fixed in #2651
