### ISSUE TITLE
0.10.4 1.el7 upgrade caused log partition to fill up in a manner of minutes - loglevel issue

### ISSUE THREAD

**Issue by ZizzyZizzy** [fail2ban/fail2ban#2581]
### Environment:

Name        : fail2ban
Version     : 0.10.4
Release     : 1.el7
Architecture: noarch
Install Date: Sat 28 Dec 2019 09:28:33 AM MST
Group       : Unspecified
Size        : 0
License     : GPLv2+
Signature   : RSA/SHA256, Sat 23 Nov 2019 04:42:22 PM MST, Key ID 6a2faea2352c64e5
Source RPM  : fail2ban-0.10.4-1.el7.src.rpm
Build Date  : Sat 23 Nov 2019 04:24:13 PM MST
Build Host  : buildvm-09.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://fail2ban.sourceforge.net/
Bug URL     : https://bugz.fedoraproject.org/fail2ban
Summary     : Daemon to ban hosts that cause multiple authentication errors

CentOS Linux release 7.7.1908 (Core)

Linux xxxx 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### The issue:

With nothing else changed, the upgrade to this version managed to cause /var to fill up in less than 10 minutes with extremely verbose debugging in the log file.

Previous loglevel was 3, which the .conf file says is INFO.

This new version now completely ignores the previous numeric log level setting and defaults to DEBUG. WOW, just wow. Seriously guys? How was this overlooked?

Either convert the previous numeric value during startup to the new word values, or crash on start because of the invalid/unrecognized setting. A default to debugging level is a horrible choice.

**Comment by sebres** [comment]
> Previous loglevel was 3, which the .conf file says is INFO

No, the log levels are counted "backwards" from 50 (CRITICAL) to 1 (extremely heavy DEBUG), thereby INFO is 20 (see https://docs.python.org/2/library/logging.html#logging-levels).
Thus level 3 is even harder as HEAVYDEBUG and would log almost every message fail2ban ever produces.

> WOW, just wow. Seriously guys? How was this overlooked?

I don't know from which version exactly you upgraded, and the log levels were always so since begin of fail2ban, but v.0.9 or before did not accepted numeric levels in configs at all. To avoid puzzling over a black box please provide previous version as well as where you've obtained it from.

Also can you point me to which of the .conf file should say it were INFO.

**Comment by ZizzyZizzy** [comment]
Previous version was **fail2ban-server-0.9.7-1.el7.noarch**

`# rpm -qi fail2ban
Name        : fail2ban
Version     : 0.9.7
Release     : 1.el7
Architecture: noarch
Install Date: Wed 02 May 2018 05:19:24 PM MDT
Group       : Unspecified
Size        : 0
License     : GPLv2+
Signature   : RSA/SHA256, Thu 13 Jul 2017 01:32:54 PM MDT, Key ID 6a2faea2352c64e5
Source RPM  : fail2ban-0.9.7-1.el7.src.rpm
Build Date  : Thu 13 Jul 2017 10:24:20 AM MDT
Build Host  : buildvm-09.phx2.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://fail2ban.sourceforge.net/
Summary     : Daemon to ban hosts that cause multiple authentication errors
Description :
Fail2Ban scans log files and bans IP addresses that makes too many password
failures. It updates firewall rules to reject the IP address. These rules can
be defined by the user. Fail2Ban can read multiple log files such as sshd or
Apache web server ones.
`

`[Definition]

# Option:  loglevel
# Notes.:  Set the log level output.
#          1 = ERROR
#          2 = WARN
#          3 = INFO
#          4 = DEBUG
# Values:  NUM  Default:  3
#
loglevel = 3
`

**Comment by sebres** [comment]
Hmm...
It looks like 5630c56c753b831055eeb238f4662b6880f2cc4a indeed had this "strange" log levels.
But as I can see the changes from this commit was already released with 0.9.0 (so first 0.9th version).

It is still a mystery to me how any of v.0.9 was able to start at all with this log level - I'll either expect an error `AttributeError: 'module' object has no attribute '3'` in `getattr(logging, value.upper())`, see https://github.com/fail2ban/fail2ban/commit/5630c56c753b831055eeb238f4662b6880f2cc4a#diff-278844de51ec45e12e6955a69cd9accbR338
Weird.

@fail2ban/maintainers any idea how it is possible as well as how such old config file (from 0.8?) can be a part of 0.9.7 version?

**Comment by sebres** [comment]
Downloaded `fail2ban-server-0.9.7-1.el7.noarch.rpm`:

`/etc/fail2ban/fail2ban.conf`:
```ini
...
[Definition]

# Option: loglevel
# Notes.: Set the log level output.
#         CRITICAL
#         ERROR
#         WARNING
#         NOTICE
#         INFO
#         DEBUG
# Values: [ LEVEL ]  Default: ERROR
#
loglevel = INFO
```

Neither I see this old config file, nor I see any possibility that this would ever work with 0.9.
